name: Documentation

on:
  push:
    branches: [ main ]

env:
  FILE_NAME: interview-questions

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest   
    
    steps:
      - uses: actions/checkout@v3 

      - name: Create output directory
        run: mkdir output
      
      - name: Create .Net fundamentals PDF
        uses: docker://pandoc/latex:2.10
        with:
          args: --pdf-engine=xelatex --output=output/${{env.FILE_NAME}}-DotNet.pdf docs/DotNetFundamental.md

      - name: Create C# PDF
        uses: docker://pandoc/latex:2.10
        with:
          args: --pdf-engine=xelatex --output=output/${{env.FILE_NAME}}-CSharp.pdf docs/CsharpOops.md

      - name: Create Angular PDF
        uses: docker://pandoc/latex:2.10
        with:
          args: --pdf-engine=xelatex --output=output/${{env.FILE_NAME}}-Angular.pdf docs/Angular.md

      - name: Upload
        uses: actions/upload-artifact@v3   
        with:
          name: output
          path: output
